# Node docker image on which this would be run
image: node:8.10.0

cache:
  paths:
    - node_modules/

stages:
  - deploy

# Deploy
Deploy:
  image: ruby:latest
  only:
    - main
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd src
    - mv cicdconfig.ts.ignore config.ts
    - sed -i 's/secretURL/$CONFIG_URL/' config.ts
    - sed -i 's/secretToken/$CONFIG_TOKEN/' config.ts
    - cd ..
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY